version: 2

default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-spark
      user: sparkns
      password: sparkns
      port: 5432
      dbname: postgres
      schema: raw
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
      
sparknetworks:
  outputs:

    dev:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [dev_username]
      pass: [dev_password]
      dbname: [dbname]
      schema: [dev_schema]

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev
